In [2]:
x = [2.3,2.5,3.6]
y = [8,9,13]

In [7]:
import scipy as sp
import scipy.stats 

In [11]:
pearson_r, p_val = scipy.stats.pearsonr(x,y)
pearson_r

0.99890610723867201

In [13]:
import numpy as np

x = [1,2,3,4,5]
y = [6,5,4,3,2]

print('covariance matrix: \n', np.cov(x,y))
print('correlation coefficient: \n', np.corrcoef(x,y))

covariance matrix: 
 [[ 2.5 -2.5]
 [-2.5  2.5]]
correlation coefficient: 
 [[ 1. -1.]
 [-1.  1.]]


In [14]:
x = [6,7,8,9,10]
y = [7,9,11,13,15]

print('covariance matrix: \n', np.cov(x,y))
print('correlation coefficient: \n', np.corrcoef(x,y))

covariance matrix: 
 [[  2.5   5. ]
 [  5.   10. ]]
correlation coefficient: 
 [[ 1.  1.]
 [ 1.  1.]]
